

services:

  database:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data
  
  backend:
    image: k4sund/backend:latest
    container_name: spring_boot_app
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    image: k4sund/frontend:latest
    container_name: react_app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network


networks:
  app_network:

volumes:
  db_data:

