spring.application.name=demo


spring.datasource.url= jdbc:postgresql://pg-3350361-kasundilumina2016-fd51.d.aivencloud.com:24658/defaultdb
spring.datasource.username= avnadmin
spring.datasource.password= AVNS_W6ko1AyVESlwkdEqaoe

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=5000